spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/order-service
    username: vladsw764
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

logging:
  level:
    root: INFO
    com.isariev.orderservice: TRACE
    org.springframework.transaction: TRACE

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost